import { Provider } from '@angular/core';
import * as converters from './converters/converters';
import * as mocks from './contractLibrary/dataServiceMocks';
export * from './contractLibrary/contractLibrary';
export * from './dataService/data.service';
export * from './dataService/view/dataServiceView';
export * from './dataService/parent/parentData.service';
export * from './singletonDataService/singletonData.service';
export * from './singletonDataService/parent/parentSingletonData.service';
export * from './resourceBuilder/resourceBuilder.service';
export { converters, mocks };
export declare const DATA_CONTRACT_PROVIDERS: Provider[];
