import * as mocks from './baseResourceBuilder/dataServiceMocks';
export declare var moduleName: string;
export * from './baseResourceBuilder/contractLibrary';
export { IBaseDataService, IBaseDataServiceFactory, IBaseDomainObject, BaseDataService, factoryName as baseDataServiceFactoryName } from './baseDataService/baseData.service';
export { IBaseDataServiceView, IBaseParentDataServiceView } from './baseDataService/baseDataServiceView';
export * from './baseParentDataService/baseParentData.service';
export { IBaseSingletonDataService, IBaseSingletonDataServiceFactory, BaseSingletonDataService, factoryName as baseSingletonDataServiceFactoryName } from './baseSingletonDataService/baseSingletonData.service';
export * from './baseParentSingletonDataService/baseParentSingletonData.service';
export { IBaseResourceBuilder, serviceName as builderServiceName } from './baseResourceBuilder/baseResourceBuilder.service';
export { mocks };
